name       : haskell-uuid-types
version    : 1.0.3
release    : 3
source     :
    - http://hackage.haskell.org/package/uuid-types-1.0.3/uuid-types-1.0.3.tar.gz : 9276517ab24a9b06f39d6e3c33c6c2b4ace1fc2126dbc1cd9806866a6551b3fd
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library contains type definitions for Universally Unique Identifiers and basic conversion functions.
description: |
    This library contains type definitions for Universally Unique Identifiers and basic conversion functions.
builddeps  :
    - haskell-cabal-install
    - haskell-hashable-devel
    - haskell-random-devel
rundeps    :
    - devel:
        - haskell-hashable-devel
        - haskell-random-devel
networking : yes
setup      : |
    sed -i "s|1.3|1.4|g" uuid-types.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
